import os
import requests

class Telegram:
  def __init__(self):
    self.telegram_chat_id = os.getenv('TELEGRAM_CHAT_ID')
    self.telegram_token = os.getenv('TELEGRAM_BOT_TOKEN')
    self.url = f"https://api.telegram.org/bot{self.telegram_token}/sendMessage"

  def send_message(self, message):
    message = message + "\n------\n**This message was generated by Omega Intelligence Suite AI.**"
    payload = {
        "chat_id": self.telegram_chat_id,
        "text": message,
        "parse_mode": "Markdown" # Permet d'avoir du gras/italique
    }
    try:
        response = requests.post(self.url, json=payload)
        response.raise_for_status()
        print("🚀 Analyse envoyée sur Telegram avec succès.")
    except Exception as e:
        print(f"❌ Erreur envoi Telegram : {e}")